### PR TITLE
Navigation overhaul - hamburger menu & drawer

### PR DESCRIPTION
**Pull request by ghys**
Use snap.js & angular-snap to add a left-hand side drawer.
Can be dragged into view by swiping right, or with the hamburger menu.
Not accessible in kiosk mode.
Also made a few adjustments in the main menu layout, and in the stylesheets.
CodeMirror updated (side-effect).

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
Screenshot of the new drawer:
image

Comments welcome.

**Comment by mdilger** [comment]
Looks like I have more testing to do tonight ;-)

**Comment by neohusky** [comment]
OMG! That's just awesome! I can't wait to test it.

**Comment by mdilger** [comment]
I like it!!  No issues so far as I am still only running my test system.

We move into our new house next week and then I will start to expand the system, i.e. many more panels and items.  

Cheers,
Mike

**Comment by ghys** [comment]
Thanks!
I've been thinking about dedicating part of the drawer (or a dedicated drawer on the right) to user-defined templates for advanced users, allowing system-wide values or even switches to be displayed in a ubiquitous way, but no clear plans yet.

**Pull request merged**
