### PR TITLE
Template functions: add getItem, rename itemValue to itemState

### PR DESCRIPTION
**Pull request by mgfriedel**
Returns all item data to the UI. This is useful for dynamically
generating HTML selects and other forms of dropdown menus:
Example habpanel Template:

```
<h4>Basement Hub</h4>
{{itemname = 'harmonyhub_hub_Basement_currentActivity';""}}
<div class="btn-group" uib-dropdown>
  <button id="single-button" type="button" class="btn btn-primary" uib-dropdown-toggle>
    {{itemValue(itemname)}} <span class="caret"></span>
  </button>
<ul class="dropdown-menu" uib-dropdown-menu role="menu" aria-labelledby="single-button">
  <li role="menuitem" ng-repeat="option in itemGet(itemname).stateDescription.options">
    <a ng-click="sendCmd(itemname, option.label);">{{option.label}}</a>
  </li>
</ul>
</div>
```

### CODE REVIEW

**Comment by ghys** [comment]
Sure!
Can you name it simply `item()` though? I think the "Get" suffix is kind of obvious?

**Comment by mgfriedel** [comment]
Sounds good! I'll update test/things to make sure there isn't a conflict.

**Comment by ghys** [comment]
Thanks, I'll take care of this when I get back home.

**Comment by LuckyMallari** [comment]
"item" might be a bit confusing for new users.
Consider this

```
<div ng-init="item in item('something')">
    {{ item.label }} // this would be ambiguous now
</div>
```

**Comment by ghys** [comment]
That's actually a good point. Maybe `getItem` is better then.

**Comment by ghys** [comment]
Finally decided for `getItem`, also renamed `getValue` to `getState` (with `itemValue` still available as an alias for compatibility purposes.
I made the necessary changes, it's now ready to merge. Thanks! 👍

**Comment by ghys** [comment]
Correction: @mgfriedel I need a sign-off for your commits. Please refer to [CONTRIBUTING.md](https://github.com/openhab/org.openhab.ui.habpanel/blob/master/CONTRIBUTING.md)

To keep things simple, you may comment here with a line like:

Signed-off-by: Mike Friedel &lt;your@email.com&gt;

and I will include it in the squashed commit - thanks in advance.

**Comment by mgfriedel** [comment]
Thanks guys, sorry for lack of response, been travelling for work. I'll
check contributing.md too but should I add my example again to the signoff?

On Jan 24, 2017 8:04 AM, "Yannick Schaus" <notifications@github.com> wrote:

Correction: @mgfriedel <https://github.com/mgfriedel> I need a sign-off for
your commits. Please refer to CONTRIBUTING.md
<https://github.com/openhab/org.openhab.ui.habpanel/blob/master/CONTRIBUTING.md>

To keep things simple, you may comment here with a line like:

Signed-off-by: Mike Friedel <your@email.com>

and I will include it in the squashed commit - thanks in advance.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openhab/org.openhab.ui.habpanel/pull/114#issuecomment-274847566>,
or mute the thread

**Comment by mgfriedel** [comment]
Signed-off-by: Mike Friedel <mfriedel@gmail.com> (github: mgfriedel)

**Comment by ghys** [comment]
Thanks @mgfriedel 👍

**Pull request merged**
