### PR TITLE
CSS code cleanup, gulp server task + background image

### PR DESCRIPTION
**Pull request by kubawolanin**
Hello!
As promised some time ago, here's some of my work on HABpanel.

- Added some tasks to Gulpfile.js (less, watch, server are primary ones)
- Converted the UI styling to LESS (easily manageable components with imports now)
- Created a structured LESS stylesheets
- Changed the font stack globally (pleasant "Roboto" is a main font now)
- Created `variables.less` for common styling adjustments
- Moved boostrap to assets so we can now use and adjust its variables
- Added background image to the html element (future: dynamically adjusted?)
- Adjusted grid margins
- Few other cleanup changes :-)

Feel free to test!
Hope I didn't introduce many bugs.
Enjoy.

### CODE REVIEW

**Comment by kubawolanin** [comment]
Now, with code from this PR you are basically able to set up a local development environment with gulp webserver chained with livereload and LESS compilation.

Wouldn't it be beneficial to create a config file pointing to openHAB instance located on other machine?

Let's say I'm developing on my Windows machine and my openHAB lives on my RaspberryPI3.
If I wanted to code with real data, I'd simply point http://raspberrypi:8080/ as my data source.
Is it doable at the moment?

**Comment by ghys** [comment]
Hi Kuba, thanks, some very interesting stuff here! Some much needed reorganization in the stylesheet area... I was contemplating making the jump to LESS for quite some time as well. Defining colors in variables should help a lot with theming (a mid-term feature). So I just tested your changes and will probably merge a good part of your work when I got time but:

- the random background image from unsplash may look cool but it cannot stay as is, it has to become at least optional and off by default - not everyone wants that. A global options object will be introduced and there could be a checkbox somewhere to enable it;
- moving widget-specific styles into separate files make sense, of course - what I was planning though is to have one for each widget in the ```app/widgets/<widget>``` folder (i.e. ```app/widgets/slider/slider.less```), then have gulp compile them to css in-place and try out [angular-css](http://castillo-io.github.io/angular-css/#/) to inject them dynamically with the widget directives.
- the settings area is broken: the blue background for the panel configs box is cut if it exceeds the screen height, and the codemirror JSON editor doesn't show up.

No config file for the moment - I always assumed the UI should be hosted by the openHAB instance and connect to it with a well-known relative URL. I made my developments using a SMB share to a clone of the repository in ```conf/html```... But I see your point, developing locally using gulp-watch and gulp-webserver make sense as well, maybe there will be another global option to connect to another openHAB instance (and pray we dont run into CORS issues)

**Comment by s-simma** [comment]
I hope HABpanel will stay a user friendly/stable interface (as it is at the moment) for everybody (beginners and developers) and not a developement environment for freeks.

**Comment by kubawolanin** [comment]
@s-simma no worries. What I propose here is a way to quickly launch an interface via node http server with tools for developers/"freeks" (like livereload after you save a file, live compilation of files etc). 
It won't impact the result...

@ghys glad you like it! Let me fix the things you mentioned here and after that we may try to merge the whole thing altogether when it's ready.

Cheers!
K

**Comment by kubawolanin** [comment]
@ghys done!

- Background image is hidden by default. Configuration tool is needed to inject `image-bg` class to the `<html>` element and possibly `style="background-image:url('path/to/custom/image.jpg')"` in the future.
- All widgets have its LESS file. They are now collected through `assets/styles.less` - I did it this way so we are still able to use local (HABpanel color pallette) and global (e.g. Bootstrap) variables.
Angular-css would be nice but I'd see it not on the widget level, but global perhaps.
- Fixed the local settings container and codemirror displays properly now.

Thanks,
Kuba

**Comment by digiltd** [comment]
@s-simma freeks? a bit harsh

@kubawolanin Well done, you have been busy. Here is some feedback:

Can I ask why you opted for Less over Sass? Just curious as whilst the two are similar, Sass is the more popular and therefore better supported preprocessor. It is also super fast when using Libsass. 

Looking at your usage of Less it seems that you are mainly using it for variables and imports. You might want to consider using this as an exercise to make the jump to Sass (well, Scss) as those two things are very straightforward to convert. 

### Variable use in Less

```less
// set the variable
@color-primary: #638b18;

// use the variable
.thing-to-style {
    background-color: @color-primary;
}
```


### Variable use in Scss

```scss
// set the variable
$color-primary: #638b18;

// use the variable
.thing-to-style {
    background-color: $color-primary;
}
```

More at http://sass-lang.com/guide

The way partials are used will be very useful to you and others looking at your files. It is fairly simple, you have the `main.scss` file that you will import the other files into. The files to be imported (partials) are named with an underscore at the start e.g. `_variables.scss`. Sass will not process individual files with an underscore as it knows they are imports. 

to import into the `main.scss` you don't have to use the underscore or the extension.

```scss
@import "variables";
```

Just to confirm, I am not saying you "should" use Sass, but there is a reason why it is so popular and Bootstrap4 is dropping Less. It is worth a look :)


#### Other feedback

You do need to comment more in your code, it is a good habit to get into and any information is better than nothing :)

You variable naming could be more descriptive 

```less

@slider-pointer:       #234;
@slider-pointer-bg:    #def;
@slider-floor:         #def;
@slider-ceil:          #def;
@slider-bubble-bg:     #123;
@slider-bubble-border: #456;
@slider-bubble-color:  #aaaa77;

// after 

@slider-pointer-color:       #234;
@slider-pointer-bg-color:    #def;
@slider-floor-color:         #def;
@slider-ceil-color:          #def;
@slider-bubble-bg-color:     #123;
@slider-bubble-border-color : #456;
@slider-bubble-color:  #aaaa77;

```

Naming variables is hard and for every valid suggested method is an equally valid argument against.

> There are only two hard things in Computer Science: cache invalidation and naming things.
> **Phil Karlton** 

BEM (Block Element Modifier) works very well and it very a very "human" approach. https://css-tricks.com/bem-101/

Naming colours is even harder, this article explains the issues well https://davidwalsh.name/sass-color-variables-dont-suck 

.... and this "comment" has gone on way longer than expected, sorry about that. Take it as you want to take it, and whatever works for you is good enough :)

**Comment by kubawolanin** [comment]
@digiltd thank you so much for the feedback!
I was thinking about Scss and the only thing that held me back was Bootstrap.
We may switch to [bootstrap-sass](https://github.com/twbs/bootstrap-sass) and then proceed with conversion.

Thanks for the suggestion regarding naming things! 
I didn't add `color` suffix anywhere to align with convention that [bootstrap follows](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss). 
Phil Karlton was right indeed - the more descriptive you are in naming things, the less readable it becomes :)

Best,
K

**Comment by ghys** [comment]
Great discussion going on here, thanks @digiltd for your insightful comments!
I have no particular gripe against Less but Sam makes some pretty compelling arguments. If we make the switch to Bootstrap 4 down the road it is clearly the better option. So I'm leaning towards Scss :)

@kubawolanin - couple of additional things:
- the settings box with panel configuration is still broken if it exceeds the screen height:
image
(height: 100% in .box classes should not apply in this case)

- I'd prefer the Roboto font to be served locally from the fonts folder instead of the CDN, I'd like to avoid relying on Internet connectivity (some even have a dedicated VLAN for their smart home installation)

- openHAB contributing rules require all commits be signed off (with the ```-s/--signoff```) option, it's explained in the CONTRIBUTING.md file. Please stash your commits and sign off when you're ready to have them merged.
Also please add yourself to the AUTHORS file, not the MAINTAINERS file (which reminds me I should add @digiltd as well 😄)

Thanks!

**Comment by kubawolanin** [comment]
@ghys @digiltd I've migrated the whole LESS code to SCSS without issues. The tricky part was augumenting bootstrap variables. I needed to [put modified variables *before* including bootstrap](https://discourse.roots.io/t/how-to-override-boostrap-variables-in-sass/3729). Interesting.
Also:
- Fixed the settings container bug
- Roboto font is now stored locally (which results now in few svg files in diff. Sorry about that)
- [*Enhancement*] Added quick `Edit` button for dashboards - it simply goes from `/view/` to `/edit/` state. Button is invisible by default - it shows when you hover over `.header` element
- I've signed-off my commits :)

**Comment by ghys** [comment]
Great work, almost there!

1) ```$body-bg``` needs to go back to black
2) the font doesn't load, relative paths are wrong:
```:8080/static/fonts/Roboto/Roboto-Light.woff:1 GET http://192.168.1.xxx:8080/static/fonts/Roboto/Roboto-Light.woff 
:8080/static/fonts/Roboto/Roboto-Regular.woff:1 GET http://192.168.1.xxx:8080/static/fonts/Roboto/Roboto-Regular.woff 404 (Not Found)
:8080/static/fonts/Roboto/Roboto-Light.ttf:1 GET http://192.168.1.xxx:8080/static/fonts/Roboto/Roboto-Light.ttf 
:8080/static/fonts/Roboto/Roboto-Regular.ttf:1 GET http://192.168.1.xxx:8080/static/fonts/Roboto/Roboto-Regular.ttf ```
2) rename ```assets/less``` to ```assets/styles```
3) rename ```$primary-bg``` and ```$widget-bg``` to ```$primary-color``` and ```$widget-design-bg```
2) your edit icon makes the dashboards move a few pixels down when it appears. It also needs to pop up only when hovering over the h2, not the whole header, and only if editing is allowed (```ng-if="!lockEditing"```)

**Comment by kubawolanin** [comment]
@ghys Thank you!
1. Done
2. Done. There's a bug on [roboto-fontface package](https://github.com/choffmeister/roboto-fontface-bower/issues/34) - it has hardcoded folder name that's uppercase. That's why it worked on my Windows and didn't elsewhere :)
3. `assets/styles` it is!
4. Done
5. Fixed container jumping caused by Edit button padding. Although I didn't change the hover. Notice that `h1` occupies the whole `header` width. When I changed it to `display: inline-block` and added some `padding-right` it fit your requirement, but caused other issues with the layout (like misplaced buttons etc). So I left it this way for now.

Also:
* Added .csscomb.json to the project so we can format the files easily. (In my [SublimeText](https://github.com/csscomb/sublime-csscomb) I just hit `Ctrl+Shift+C` :))
* Reformatted some HTML and JS files as well (I use ESLint Formatter and we could think of placing `.eslintrc` file in the project root some day)

Peace!
K

**Comment by ghys** [comment]
Thanks a lot for all your work this weekend @kubawolanin!
The Roboto font was still not loaded but fixed it.

Regarding the header, now that it doesn't move it's not that important - the reason was, when I tap the back or home button on a tablet, the edit button appears for a short time and that would cause the widgets to move.

I intended to use ESLink a while ago and put a ```.eslinkrc.yaml``` file but never went further :)

Thanks again.

**Pull request merged**
