### PR TITLE
Internationalization/localization effort for HABPanel

### LINKED ISSUE #131: Support for Translations
First things first. Thank you for the tremendous effort put into this project.
What caught my eye was the missing possibility to select a language for habpanel.
That would be pretty nice to have and could be accomplished by using something like [angular-translate](https://github.com/angular-translate/angular-translate).

Keep up the good work. ;)

Dennis

### PR DESCRIPTION
**Pull request by ghys**
Resolves #131 (in part).

This adds locale support to HABPanel for more than 150 languages and regions.
The locale configured in ESH (org.eclipse.smarthome.core.i18nprovider) is used.

Not all contents of angular-locale are included to limit the size overhead:
only the region-less variant of each language is considered except for the
following locales (arbitrary list, more can be added later):

- es-ar
- de-at
- en-au
- fr-be
- es-bo
- pt-br
- en-ca
- fr-ca
- fr-ch
- es-co
- en-gb
- en-hk
- zh-hk
- en-ie
- en-in
- fr-lu
- es-mx
- en-nz
- en-sg
- zh-sg
- es-us
- zh-tw
- en-za

Note: some dependencies in vendor.js were updated in the process.

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
Some additional info on this - the total weight of the locales is 756kb:
```
$ du -hs web/vendor/i18n
756K    vendor/i18n
```

The chart, timeline widgets and the side drawer bottom are the most obvious places where this change is visible. I don't plan to completely translate the entire interface for now.
I have no idea whether RTL languages are properly rendered (full RTL support is not planned):

image
image

An important side effect: if no language is found (Paper UI > Configuration > System) it will now default to *mostly* US English with a few exceptions, meaning 12-hour (except in the chart/timeline axis labels) and month-day-year order for dates (except in the drawer) - which might be unwanted!

image

To get the full US English format in the drawer, the English language and United States region has to be explicitely set:

image

Holding off the merge until I can perform further testing. If anyone is interesting in reviewing now is the time ;)

**Comment by ghys** [comment]
Hey @ThomDietrich & @kaikreuzer 👋 

Although this was long and boring, I slowly but surely added internationalization for HABPanel, mostly in https://github.com/openhab/org.openhab.ui.habpanel/pull/256/commits/33e2128a0bfd1e57f17d74614c4c2081b58778c4.

I understand Crowdin is the platform of choice for localization management across openHAB projects - so if you think it's a good fit for HABPanel as well, may I ask you to help me set it up?

Thanks in advance!

---

A few implementation details:

The language and region to use for both string translations as well as date/time/number formatting is retrieved from the i18nProvider via the REST API.
The translations are splitted into 3 .json files in separate folders - _main_, _admin_ and _widgets_. I have made a complete translation in French as a starting point, and a skeleton German one (might not even be good) with only a few strings:
- https://github.com/ghys/habpanel/blob/i18n/web/assets/i18n/main/fr.json
- https://github.com/ghys/habpanel/blob/i18n/web/assets/i18n/admin/fr.json
- https://github.com/ghys/habpanel/blob/i18n/web/assets/i18n/widgets/fr.json
- https://github.com/ghys/habpanel/blob/i18n/web/assets/i18n/main/de.json
- https://github.com/ghys/habpanel/blob/i18n/web/assets/i18n/admin/de.json

The reason for this split is, the lightweight _main_ alone is enough to display the dashboards (it also contains a few common terms), and _admin_ and _widgets_ are only loaded as needed when you enter the configuration screens.

Moreover, an incomplete translation where for instance only _main_ is translated would be OK already; the untranslated admin/widget screens would remain in English. That's why we don't need the English strings and the .json files for English are empty - they are still "hardcoded" like before and act as defaults.

**Comment by LuckyMallari** [comment]
Nice work on the ng-translate. Let me know if you need some assistance. We use ng-translate heavily on our Angular1.x here at work. What we found extremely useful is to use KEYS in ALL CAPS, which makes it super easy to spot on the template. 

Do you also plan to use nested translation?
example:
```
{
    ...
    "key1" : "Hello {{key2}}",
    "key2": "Lucky"
    ...
}

<span translate="key1" />
resolves to "Hello Lucky"

** Nested translation is not supported out of the box by ngtranslate
```

Also, ng-translate adds TONS of watches. So for static stuff, it is best to use one-time binding:
```
<span>{{ ::("key1" | translate) }} </span>
```

**Comment by ThomDietrich** [comment]
Hey @ghys, great stuff!
We are trying to organize all translations related discussion in https://github.com/openhab/openhab-core/issues/275 - Be sure to leave a comment.

As for how and what: After you are finished and the branch is merged, we can go ahead and create the crowdin project. After first experiments in the openhab-android project we decided that it is best when both the crowdin project and the GitHub integration are done through the "openhab-bot" account. Kai (or me) will do that for you as soon as you tell us to. You can check the potential result here: https://crowdin.com/project/openhab-android

**Comment by ThomDietrich** [comment]
Regarding the specifics of this project: Your split into three files is not an issue. I saw that your `en.json` are currently empty. Those would be the source for crowdin and you'd definitely need to provide them.

Crowdin can handle json files, however with json files there are a few limitations of Crowdin you should be aware of. If you can switch to another file type easily, maybe that would be something to consider (xml or ini both work nice).

1. Blank lines are removed from the generated translated files
2. There are no comments in json (that's a given), which sadly means you can not give context information for translators. Especially for short strings missing context is often an issue.
3. Not yet translated strings will be translated as empty strings, [see here](https://github.com/openhab/openhab-core/pull/244/files#diff-504e0d71b363d462229c087fee131ec6). I know this is not ideal and I already talked to the crowdin support about it, sadly they can't (won't) change their exporter now.
   Consequently that means that you have to handle the case of an empty string as if no string was given and present the default translation.

**Comment by ghys** [comment]
> Let me know if you need some assistance. 
> What we found extremely useful is to use KEYS in ALL CAPS, which makes it super easy to spot on the template.

I think most of the grunt work is now done - if you see anything missing or would like to contribute translations, that would be cool. I chose lowercase for the keys, too late now I guess, I'm not changing all 500+ of them to all caps now!

> ng-translate adds TONS of watches

Yes, when using the filter, that's what the doc says anyway, so I mostly used the directive; there are exceptions notably for tab headers and in other places when the text to translate is in a attribute (I couldn't use the `translate-attr` because I wanted to keep English as a default instead of displaying the key when the translation is missing).

**Comment by ghys** [comment]
> I saw that your en.json are currently empty. Those would be the source for crowdin and you'd definitely need to provide them. Crowdin can't extract those from your various code parts.

That's what I suspected, I'll come up with a solution (see below). What I didn't want is to have only translation keys in the code, but keep the current English text in place as much as possible for context (and to be honest, because it was far too much work to move everything around ;))

> Just to be clear about regional translations, there could be de.json and de-at.json in parallel?

Currently no, only the "language" part of the locale is considered, not the region, but this could be done - although the regional variants would have to be known by the angular-translate library so it could fall back to e.g. 'de' if 'de-at' doesn't exist (it can't figure it out automatically).
See https://angular-translate.github.io/docs/#/guide/09_language-negotiation

> Crowdin can handle json files, however with json files there are a few limitations you should be aware of. If you can switch to another file type easily, maybe that would be something to consider (xml or ini both work nice).

About the format of the files, unfortunately the framework only supports .json, so I added blank lines and - hopefully - came of with self-explaining keys with namespaces and logical ordering so that the context would be clear enough; otherwise, I was thinking about using gettext [PO files](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) as a source and then using a gulp task (used for building HABPanel) to convert them into .json files if necessary (or let crowdin generate the .json): there are already stuff we can reuse:
- http://blog.edenhauser.com/using-gulp-to-compile-po-files-to-json-for-e-g-angularjs-translate/
- https://github.com/angular-translate/grunt-po2json-angular-translate (that's for grunt, not gulp, but anyway).

That way the translation context could be added to the PO files and uploaded to crowdin - all of this seems to be supported -, then it doesn't really matter if the resulting "compiled" .json files have no logical structure if the context is kept elsewhere.

I'm sure I can come up with some script to generate those PO files from my current fr.json files, for the keys at least, and then use that to make some with the English text.

> Not yet translated strings will be translated as empty strings, see here. I know this is not ideal and I already talked to the crowdin support about it, sadly they can't (won't) change their exporter now. Consequently that means that you have to handle the case of an empty string as if no string was given and present the default translation.

Not ideal indeed, but there are workarounds too. Either another gulp task to remove the keys with empty strings, or a way to ignore them at runtime.

I'll let you know when I have something we can work with!

**Comment by kubawolanin** [comment]
Hey @ghys just wanted to express my gratitude. Awesome stuff! 🎊 
Too bad I couldn't jump on board, helping you with boring stuff there. 

I'll make sure all the strings are translated to Polish! :-)

**Comment by ThomDietrich** [comment]
Sounds great @ghys!
Crowdin retrieves source files from the repository and provides them back in the same file typ and format for translated languages. Paths for source and destination can be defined using placeholders. Everything you can do to allow that process would be fine, be it json or po is totally up to the degree of freedom and functionality you are willing to provide.

Regarding regional dialects: that's not a priority on my side, just wanted to mention it. One user contacted us and was eager to provide Basilian Portuguese translations for openhab-core. That might happen for habpanel as well some day.

**Comment by hakan42** [comment]
> I'll make sure all the strings are translated to Polish! :-)

Count me in for Turkish too, I really want my Granny to easily command my home 😄

**Comment by ghys** [comment]
@ThomDietrich still in the experimentation phase 😄 ... and I'm doing exactly that 😁 
https://crowdin.com/project/ghys-habpanel
Making use of the 10-day trial...
It seems to be going well!

image

There was some weird problems - it didn't import the French strings which were the same as English, but I could upload them manually.

What's cool with PO files is that we can add both comments and "msgctxt" lines (for ids) in the source files (en.po) and Crowdin will automatically put both of them in its "context" box while preserving the structure.

I just sent you an invitation if you want to take a look!

**Comment by ghys** [comment]
@ThomDietrich I have a working workflow with crowdin now! 🎉
I have to run `gulp i18n` to convert updated .po files to .json, so the crowdin PRs won't enough, but that's not really an issue.

So I'm ready to have the crowdin project created under @openhab-bot when you're ready. 😉 
This PR is now merged to master, with the crowdin.yml file, so it should pick up the correct configuration for the GitHub integration (I think?).

I left the French translation out of this PR - we'll try to add it in a separate PR through crowdin as an exercise to validate the workflow! (I still have the .po files we can upload)

Cheers!

**Comment by kaikreuzer** [comment]
Project created with @ghys being manager: https://crowdin.com/project/openhab-habpanel

Github integration is done and sync'ed, but I see some error being displayed:

screen shot 2018-01-18 at 17 34 09

**Comment by ThomDietrich** [comment]
@kaikreuzer the same error is shown for the openhab-android project. It's caused by the fact that we have regional dialects as target and those need to be added as exceptions under Language Mapping. I sadly can't do so. If we remove these translations the error is dismissed (just tested). You'd need to add pt-BR and I've removed Traditional Chinese for now.

**Comment by ThomDietrich** [comment]
@ghys looks really good!
I've updated the target languages to be the same as for openhab-android and I've updated the project description.

**Comment by ThomDietrich** [comment]
No it's not. The list is the default by crowdin plus a few selected ones users asked for. I am yet to decide on a full list of languages and/or how to manage languages without translators. Sadly crowdin doesn't yet offer an automated way to request a new translation to be added as an option. You need to contact a manager to have a language added.

**Comment by ThomDietrich** [comment]
@ghys btw. I've added the openHAB basic glossary. What you could additionally do is upload screenshots showing the strings in action. That'S a nice additional feature. See e.g. https://crowdin.com/translate/openhab-android/7/en-de --> "Select default sitemap"

**Comment by ghys** [comment]
Yes good idea!
The comments I added might be enough in some cases but screenshots definitely are a plus.
I'll add HABPanel terms to the glossary so that e.g. the difference between a "panel" and a "dashboard" is understood and translated correctly, I saw it's highlighted and the definition appears in the translation UI, really nice.

**Comment by ghys** [comment]
This glossary thing is actually quite brilliant really :)

image

**Pull request merged**
