### PR TITLE
Add proper documentation

### PR DESCRIPTION
**Pull request by ghys**
See #138.

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @ghys, this looks excellent - what keeps you away from merging it?

**Comment by ghys** [comment]
@kaikreuzer I had the ambition to write a whole chapter about custom widgets and template development before merging it but never got around to it ;) But yes, baby steps, it's quite useable in this state already, and I suppose a link to the relevant new section on community.openhab.org is enough for now. So I'll just made a few corrections and merge it.
@ThomDietrich could you have a look too?

**Comment by ThomDietrich** [comment]
Totally missed that request... :-/ Had a look now and must say, that's an excellent article ;)
What's the next step, do you want merge with and/or replace http://docs.openhab.org/addons/uis/habpanel/readme.html or is the article supposed to stay independent?

**Comment by ghys** [comment]
@ThomDietrich my intent was to keep them independant, i.e. leave the readme.html article as it is (for a general description of the addon, similar to those of the other GUIs) and have this more extensive documentation elsewhere in the tree - perhaps under 'Configuration'?
It should link properly to the other parts of the documentation (I hope), I tried to imitate other articles and put {base} in the URLs.

It's more convenient, I can submit a PR to the openhab-docs repo.

**Comment by ThomDietrich** [comment]
Sure thing, makes total sense :+1: let's replicate the configuration article to docs and link it to a menu entry in parallel to http://docs.openhab.org/configuration/paperui.html

PR welcome. ;)

**Pull request merged**
