### PR TITLE
Add scm connection info to pom.xml

### PR DESCRIPTION
**Pull request by pfink**
_This is a cross-repo change which is part of the implementation of a release automation process for openHAB_

This adds scm connection info to the pom.xml which is used by release automation processes to push changes, create tags etc. The property `scm.gitBaseUrl` is taken from the parent pom within the openhab-core component https://github.com/openhab/openhab-core/blob/a1e10ccea71189991fb542e4251ac8bee04c4c91/poms/pom.xml#L51 and makes it possible to easily make "sandbox releases" on separate repositories. Within the `url` tag, the `scm.gitBaseUrl` is intentionally not used because in discussions with @kaikreuzer I agreed that we aim to keep the pom.xml human-readable without always having to lookup properties from the parent pom(s). As the `url` tag is just a meta information and not used by any automation process, it's no problem to hard-code the production repo there.

Signed-off-by: Patrick Fink <mail@pfink.de>

### CODE REVIEW

**Comment by ghys** [comment]
@pfink thanks the detailed explanation, looks good!
I'm assuming it is, but just to double check ("trust, but verify" as the proverb says 😉) - is it safe to merge now?

**Comment by pfink** [comment]
Totally yes - I think habpanel is the last component, for all the others the change is already merged :)

**Comment by pfink** [comment]
Btw, formatting of your POM is a little bit broken, beautifying would be nice. If you like, I could do that as well.

**Comment by ghys** [comment]
Uh, you're right about the formatting, kind of ugly...
If it's not too much of a hassle for you, yes absolutely, feel free to go ahead and add a fix for the formatting to this PR - let's kill two birds with one stone.

**Comment by pfink** [comment]
Done!

**Comment by ghys** [comment]
Many thanks, merged!

**Pull request merged**
