### PR TITLE
Added position:relative to .gridster-mobile .box-content except .editMode

### LINKED ISSUE #273: Backdrop/Icon out of place
Backdrop out of place when in responsive mode
Steps:
Add a switch (or any widget)
Add a backdrop icon
Enable dashboard responsive mode (Mobile mode)

image

Issue:
box-context is not positioned properly

### PR DESCRIPTION
**Pull request by LuckyMallari**
Added position:relative to .gridster-mobile .box-content position relative
Gulped
Fixes #273

Signed-off-by: Lucky Mallari <luckymallari@gmail.todotcom>

### CODE REVIEW

**Comment by ghys** [comment]
Still not comfortable changing a sensitive class like this to solve a minor bug in the unsupported mobile mode...
Gridster apparently adds the `.gridster-mobile` class when in mobile mode so you could rewrite this like this:
```
.gridster-mobile .box-content {
   position: relative;
}
```
so that no impact is guaranteed outside it.

**Comment by LuckyMallari** [comment]
Done. I still had to add an .editMode class to the one inside dashboard.edit since in all modes (mobile or not) its position has to be not set since positioning it will disable draggable. Still should not affect anything else after adding the .gridster-mobile class to the css

**Comment by ghys** [comment]
> Done. I still had to add an .editMode class to the one inside dashboard.edit since in all modes (mobile or not) its position has to be not set since positioning it will disable draggable.

I don't understand why? The dashboard designer will never be in mobile mode.

**Comment by LuckyMallari** [comment]
LOL. I had an external css defined and conflicting with whatever you've been saying so now we're on the same page. Done with changes

**Pull request merged**
