### PR TITLE
Handle SSE audio events

### PR DESCRIPTION
**Pull request by ghys**
Saw [this](https://github.com/eclipse/smarthome/pull/2314) by accident :)
I'm in too! :)

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Ha, very cool! I also intended to point you to this as I definitely had HABPanel in mind for this feature 👍

**Comment by ghys** [comment]
@kaikreuzer Sure, it's a great new ESH feature! I must admit I haven't tested it but I figured simply borrowed Paper UI's implementation would work - and it was so easy to implement.

I also noticed a lot of work went into text-to-speech and speech-to-text in ESH lately... as HABPanel already has a text-to-speech feature (monitoring an item, which is not ideal), I was wondering if the same kind of SSE-driven mechanism could be done for TTS as well? Like a "SSE TTS Service"?

**Comment by kaikreuzer** [comment]
When I saw your TTS support, I was thinking about this myself. The problem is that a TTS in ESH takes a text in and is expected to spit out an audio stream - this obviously won't work with an SSE TTS service. We might need to enhance the TTS interface to also allow the option to NOT deliver a stream, but to indicate that the services does the playback by itself. Feel free to enter an issue at ESH to further discuss this.

**Comment by kaikreuzer** [comment]
> I must admit I haven't tested it but I figured simply borrowing Paper UI's implementation would work

Maybe you should test it - I tried it with todays build and I didn't hear anything (although I saw the event being received on the JS console).
If you have the demo setup, you can simply type "audio play webaudio doorbell.mp3" on the openHAB console for testing.

**Comment by ghys** [comment]
So much for blindly adding things without testing them...
I actually tested it this time - thanks for reporting it @kaikreuzer!

**Pull request merged**
