### PR TITLE
Added prompts to ALL widget removal/deletion (in Dashboard or Widget …

### PR DESCRIPTION
**Pull request by LuckyMallari**
Added prompts to ALL widget removal/deletion (in Dashboard or Widget Settings modal)

Uses translation keys:
~~dashboard.dialog.removewidget.title~~
~~dashboard.dialog.removewidget.message~~
designer.dialog.removewidget.title
designer.dialog.removewidget.message
since all widget removal will only occur on a dashboard edit page

Signed-off-by: Lucky Mallari <luckymallari@gmail.com>

Referencing #262 
Referencing #263

### CODE REVIEW

**Comment by LuckyMallari** [comment]
Note that I am using this translation key:
dashboard.dialog.removedwidget.title
dashboard.dialog.removedwidget.message

since all widget removal will only occur on a dashboard edit page

**Comment by ghys** [comment]
Cool!
Since you introduce a new translation key you have to add it here:
https://github.com/openhab/org.openhab.ui.habpanel/blob/f90bb3448144ca05fedc11d1f8c6225f3fdef6c0/web/assets/i18n/admin/admin.pot#L81

Maybe use the same "designer" prefix too?
`designer.dialog.removewidget.title`, `designer.dialog.removewidget.message`

**Comment by LuckyMallari** [comment]
I'll do that when I get home. That's my concern, although I think it's necessary. You will have to mention this on the Contributing.md file. Every new text introduced will need to have a corresponding key to the language files.

**Comment by LuckyMallari** [comment]
@ghys done

**Comment by ghys** [comment]
Alright thanks! lgtm but I'll wait a little until I add other strings to translate so we don't bug the translators too much (I've noticed I missed a few) - we're not in a hurry.
Good point about the contributing file.

**Pull request closed without merging**
