### PR TITLE
Settings, theme & background image

### LINKED ISSUE #32: Change color of background or set image as background
The color of the background should be made choosable by user. At the moment the background is only in black. The page/dashboard color should be editable or even better there should be the possibility  to take a personal image as background.

Greetings Nic

### PR DESCRIPTION
**Pull request by ghys**
I made 4 initial themes to explore the possibilities.

### How to contribute a new theme:

Add a folder in `web/assets/styles/themes` by copying an existing one,
change varibles, override styles, and reference it in
`assets/styles/themes/themes.json`.
Then run `gulp sass` in the web folder.

Closes #32 (not the exact request but still)

Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by Nic0205** [comment]
Hey guys,

tried the new theme feature but can´t get it work.

The folder web/assets/styles/themes does not exist. The last folder is web/assets/styles/

What am I doing wrong?

Greetings Nic

**Comment by neohusky** [comment]
@Nic0205
When I downloaded habpanel from git with the merged changes It worked for. 

@ghys The new theme system is awesome I can't wait to see what people come up with. At some point a gallery of user contributed themes may be required to showcase some of the talents of other users and help share their work.

**Comment by Nic0205** [comment]
@neohusky and @ghys:

The folder now is there. I modified the .json-file and just do not know how to choose the themes?
Is there a setting in the ui or do I have to modify more files?

Greetings
Nic

**Comment by ghys** [comment]
You don't have to modify any json file unless you want to add another
theme. The option is under advanced settings (bottom right in the main
menu).

**Comment by Nic0205** [comment]
Hmmm - it´s really strange. First I installed habPanel via PaperUI. I then deinstalled it with paper ui and then cloned the GitHub with ` sudo git clone https://github.com/openhab/org.openhab.ui.habpanel.git` in my /opt/openhab2/conf/html folder.

After a reboot the files under /opt/openhab2/conf/html/org.openhab.ui.habpanel are not there anymore and when I call ...:8080/start/index then I see an habpanel entry.

When I click on this entry, there is the possibility to change / load an old configuration of mine.

But when I click the settings icon in the main menu, there is no option for themeing.

There are just the following options:

`Current storage configuration:

 Local storage 
The configuration is saved for this browser and device only. Will remain as long as you don't clean up the browser's historical data. 
Show local configuration object (experts only) 

 Panel configuration: LiNaDo 
Last synced on Sun 18 Sep 15:33:26
Contains:
LiNaDo`

what am I doing wrong?

**Comment by neohusky** [comment]
@Nic0205

Just download the git repo and copy the web folder contents into your HTML folder.

**Comment by Nic0205** [comment]
Perhaps i am simply to stupid...

In whitch directory do I have to Clone the git repo? 

Could I Clone it to /opt/openhab2/conf/html/habpanel ?

After i Cloned it to this directory  i have to copy the content of the web subdirectory direct in  /opt/openhab2/conf/html right?


Am 6. Oktober 2016 23:04:54 MESZ, schrieb neohusky <notifications@github.com>:
>@Nic0205
>
>Just download the git repo and copy the web folder contents into your
>HTML folder. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/org.openhab.ui.habpanel/pull/33#issuecomment-252088234

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by neohusky** [comment]
Simply copy the git contents of the web folder directly into the HTML folder /opt/openhab2/conf/html. No subfolders such as habpanel.  

This then accessible via web site http://ipaddress:8080/static/

**Comment by ghys** [comment]
Or you can wait a few days at most and it will end up in the repository, so you can upgrade from there (an uninstall/install will force the upgrade I think, YMMV).

The date of the last CI build if shown here: https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/lastStableBuild/org.openhab.ui$org.openhab.ui.habpanel/

I don't know in terms of process and delays what's involved to then make those builds available for download from Paper UI, maybe @kaikreuzer can chime in on this?

**Pull request merged**
