### PR TITLE
Optional floating speech button

### LINKED ISSUE #111: Enhancement : Floating Speech Button
Just due to the size of the speech comment button.  What do you guys think of making it possible to have it also as a floating style button as below.  

It's not going to be suited to all so possibly have a setting whether to display or not?

image

### PR DESCRIPTION
**Pull request by kubawolanin**
Resolves #111 

Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>

### CODE REVIEW

**Comment by ghys** [comment]
- You can use `uib-tooltip` for the big speech button but I prefer you leave the header buttons as they are, those tooltips kind of get in the way while not adding real value and they are not consistent with the other screens.
- Please `--amend` your commit without staging files in `vendor/*` if there are no changes in the dependencies - you're actually downgrading Angular to 1.5.9!

Thanks :)

**Comment by kubawolanin** [comment]
Oops! I need to commit these auto-generated files more carefully. 
It would be perfect to have them ignored and let build server handle them! ^_^
But sure, I will fix these.
Thanks for the review

**Comment by kubawolanin** [comment]
@ghys All's done now! Thanks again

**Comment by ghys** [comment]
Perfect! Thx ;)

**Pull request merged**
