### PR TITLE
Added refresh feature to image widget

### PR DESCRIPTION
**Pull request by andreasgebauer**
Signed-off-by: Andreas Gebauer <an.ge.ber.81@gmail.com> (github: andreasgebauer)

### CODE REVIEW

**Comment by ghys** [comment]
Whoops!
Did I miss this @andreasgebauer?

**Comment by ghys** [comment]
It seems we did it at the same time :)
And your implementation is better...

**Comment by ghys** [comment]
Thanks and sorry for that! I borrowed your code and merged it in #90.

**Comment by andreasgebauer** [comment]
Yes, we did it concurrently. In future I'll comment on issues as soon as I start working on them in order to don't do work twice :)

**Pull request closed without merging**
